### ISSUE TITLE
Dependency on openxlsx

### ISSUE THREAD

**Issue by novica** [NorwegianVeterinaryInstitute/NVIpretty#23]
I haven't looked at this in details but it feels like this package should not have dependncy on `openxlsx`.

If i want to add it to other packages then the whole process become bloated by adding `openxlsx` where it is not needed. 

Other dependencies for packages that are not essential for the theme to work should be removed too, again, I am saying this without having looked at the details.

**Comment by PetterHopp** [comment]
The main/ most used function in NVIpretty is add_formatted_worksheet. This function styles Excel worksheets for report. The function is used extensively in outbreak reports and in planning of surveillance programmes.

openxlsx was chosen as it has several possibilities for formatting Excel worksheets. 

To remove the dependency of openxlsx mens either to totally change the way these data is reported or to find another package to do the same task.

I'll close this, but we can discussion this further and have a look on how to reduce the number of dependencies in NVIverse packages
